### ISSUE TITLE
get_language can return None

### ISSUE THREAD

**Issue by dnmellen** [julianwachholz/django-autocompletefilter#1]
Hi! I'm trying your django package but I found an error setting it up. In my project get_language() returns `None` and the admin crashes when it tries to get the absolute paths of the js files

This can be fixed just by adding a default value here:
https://github.com/julianwachholz/django-autocompletefilter/blob/12b3cb91c14011236581d482bc3bea9442e3dbba/autocompletefilter/admin.py#L13

Or just including `i18n_name` path when is not None.

**Comment by julianwachholz** [comment]
Hi @dnmellen! Thank you for reporting this issue, I think this should be fixed now.
Sorry for the late reply, I never noticed any activity here!
