### ISSUE TITLE
Can you give me some examples about the step

### ISSUE THREAD

**Issue by ZUDQQQ** [julianwachholz/django-autocompletefilter#15]
Can you give me some examples about this step

3. Create and register a model admin for the model you want to filter by. Ensure it has search_fields specified for autocomplete to work.

4. In your second model admin, use the AutocompleteFilterMixin on your class and add the desired foreign key attribute to filter by to the list_filter items by using the AutocompleteListFilter class:

**Comment by julianwachholz** [comment]
Hi! Thank you for your question.

For this app  to fully function, you ideally want two models with a [ForeignKey](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey) or other [relationship](https://docs.djangoproject.com/en/4.1/topics/db/examples/many_to_one/) between them. 

Lets say you have a  `Book` and `Author` model.

To filter books by their author with an autocomplete filter, first [register the Author model](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#the-register-decorator) with a [`ModelAdmin`](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin) with at least [`search_fields`](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields):

```python
@admin.register(Author)
class AuthorAdmin(admin.ModelAdmin):
    search_fields = ("name",)
```

Then, configure your Book ModelAdmin with the [`AutocompleteListFilter`](https://github.com/julianwachholz/django-autocompletefilter/blob/739f8c7effe8a660f8796b7a63963f22c695b499/autocompletefilter/filters.py#L21), an example is already in the [README](https://github.com/julianwachholz/django-autocompletefilter#usage).

**Comment by ZUDQQQ** [comment]
thanks for your answer sir, but what if after i choose what to filter then the data will be filtered
