### ISSUE TITLE
Use GitHub actions for deployment process

### ISSUE THREAD

**Issue by Mogost** [julianwachholz/django-autocompletefilter#19]
@julianwachholz do you need help with that? It looks very simple to implement, and realizing right from GitHub can make your life a little simpler.

**Comment by julianwachholz** [comment]
I'd welcome this addition! Thank you. I've recently been slowly upgrading other projects to Poetry + Ruff. Integrating with GH Actions would be nice, too.

**Comment by Mogost** [comment]
I like ruff very much. But poetry is not for me. If you like ruff too take a look to another astral's solution https://docs.astral.sh/uv/

**Comment by julianwachholz** [comment]
I'm aware of `uv` but haven't yet checked it out.
