### ISSUE TITLE
Register 2 modelAdmin

### ISSUE THREAD

**Issue by tboulogne** [julianwachholz/django-autocompletefilter#2]
Hello,

Could you give an example for setting your module please ?

Thanks in advance

Thierry

**Comment by julianwachholz** [comment]
Hi Thierry, what do you need help with? The [usage section of the README](https://github.com/julianwachholz/django-autocompletefilter/blob/master/README.rst#usage) contains simple instructions on how to integrate it with your Django 2.0 Admin site!

**Comment by julianwachholz** [comment]
Closing due to old age.
