### ISSUE TITLE
Any options to keep selected result after page refreshed?

### ISSUE THREAD

**Issue by PaleNeutron** [julianwachholz/django-autocompletefilter#8]
I found this filter will submit search query after `change` event immediately, and will not keep the selected label in the widget.

Can you keep it so that users won't forget this filter is already applied.

**Comment by julianwachholz** [comment]
Hi @PaleNeutron, thanks for creating an issue! It looks like you're experiencing a bug, as the currently selected value should display in the autocomplete widget when a filter has been applied!

For example I select my username and the URL contains `?user__id__exact=1` my filter will look like this:
![image](https://user-images.githubusercontent.com/519966/75327099-19c8cb00-587c-11ea-8ad2-9099f1485a59.png)

Can you give more details on what versions of Django and Python you are using?

**Comment by PaleNeutron** [comment]
Sorry, I can't regenerate that, maybe some unstable bug during development, for example, js cache.

Thanks for reply.

**Comment by julianwachholz** [comment]
Hey @PaleNeutron did you have any luck with this? I'd like to help you get this fixed. Do you have a foreign key with a primary key that is not an integer field maybe?
