### ISSUE TITLE
Fails to render with Django 3.2

### ISSUE THREAD

**Issue by tari** [julianwachholz/django-autocompletefilter#9]
Django 3.2 seems to have [changed how admin autocomplete works](https://github.com/django/django/commit/3071660acfbdf4b5c59457c8e9dc345d5e8894c5#diff-6c1fd2d8e05936979dbe3cedc5fb6df970e6044ef524078155cd8835833008c7R383), so views using `AutocompleteListFilter` fail to render because `admin:app_model_autocomplete` views no longer exist. Instead there seems to be a new global (shared among all models) `admin:autocomplete` view.

For instance, autocomplete against a user ends up like this:
```
Reverse for 'auth_user_autocomplete' not found. 'auth_user_autocomplete' is not a valid view function or pattern name.
```

**Comment by julianwachholz** [comment]
Thank you for the report @tari! I implemented a fix to work with the new generic autocomplete view in the Django admin which you can try out in the pull request if you want. I will test this with various Django versions in the next few days.

**Comment by SebCorbin** [comment]
@julianwachholz could we have a release with this? (Tested, and works)

**Comment by julianwachholz** [comment]
@SebCorbin [0.0.7](https://pypi.org/project/django-autocompletefilter/0.0.7/) is now available :)
